### ISSUE TITLE
20 key counterbore

### ISSUE THREAD

**Issue by fi0** [dotdash32/Cases#3]
Does it make sense to add counterbore to the screw holes? or is it not recommended?

**Comment by dotdash32** [comment]
Counterbore for the old 3D printable version, or on the new one (image posted yesterday, potential GB)?  The thought with the 3D printable version is that the screws can come up from the bottom, so the hole don't need to be counterbored, since they can actually be hidden by just adding a bit on the bottom to fill the hole from the bottom (printer-facing) side.  For the picture, the thought was to have the hi-profile portion be laser-cuttable, so it has to be essentially a 2D extrusion.  The screws are button heads, so they are pretty flat and blend relatively well.  Countersunk is not out of the question for a potential CNC case, but I want to have a lower cost Acrylic case option as well.

**Comment by fi0** [comment]
thanks for the explanation!
